#!/usr/bin/env node
/**
 * Scans every server in the official MCP registry with guardmcp's static
 * (config-level) rules and writes the raw results plus a summary report.
 *
 * What it does, in order:
 *   1. Pages through registry.modelcontextprotocol.io/v0/servers?version=latest
 *      (or reads a previously saved snapshot with --snapshot).
 *   2. Turns each server's `packages` and `remotes` into an MCP client config
 *      (`{ "mcpServers": { ... } }`) — the config a user would end up with
 *      after installing it. See renderPackage / renderRemote for the rules.
 *   3. Runs the BUILT guardmcp CLI (`dist/cli/index.js scan`) over those
 *      configs, in JSON and SARIF form. No `--live`, no `--registry`: no MCP
 *      server is started or contacted, and no package registry is queried.
 *   4. Writes registry-snapshot.json.gz (exactly the input that was scanned),
 *      findings.json, summary.json and README.md into the output directory.
 *
 * Every number in README.md is computed here from the scan output; nothing in
 * it is written by hand.
 *
 * Usage:
 *   npm run build
 *   node scripts/registry-scan.mjs                       # fetch live, then scan
 *   node scripts/registry-scan.mjs --snapshot <file.gz>  # re-scan a saved snapshot
 *   node scripts/registry-scan.mjs --out <dir>           # default: docs/research/registry-2026-09
 */
import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { gunzipSync, gzipSync } from 'node:zlib';

const execFileAsync = promisify(execFile);

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));
const CLI = join(REPO_ROOT, 'dist', 'cli', 'index.js');
const REGISTRY_API = 'https://registry.modelcontextprotocol.io/v0/servers';
const PAGE_LIMIT = 100;
const SCAN_BATCH = 400;
const OFFICIAL_META = 'io.modelcontextprotocol.registry/official';

// ---------------------------------------------------------------- arguments

function parseArgs(argv) {
  const options = { out: join(REPO_ROOT, 'docs', 'research', 'registry-2026-09') };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--out') options.out = resolve(argv[++i]);
    else if (arg === '--snapshot') options.snapshot = resolve(argv[++i]);
    else throw new Error(`Unknown argument: ${arg}`);
  }
  return options;
}

// ----------------------------------------------------------------- fetching

async function fetchJson(url) {
  let lastError;
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      const response = await fetch(url, { signal: AbortSignal.timeout(60_000) });
      if (!response.ok) throw new Error(`HTTP ${response.status} for ${url}`);
      return await response.json();
    } catch (err) {
      lastError = err;
      await new Promise((r) => setTimeout(r, 2 ** attempt * 1000));
    }
  }
  throw lastError;
}

/** Only the fields the scan reads, so the committed snapshot stays small and
 * is exactly the input the numbers were computed from. */
function project(entry) {
  const server = entry.server ?? {};
  const meta = entry._meta?.[OFFICIAL_META] ?? {};
  return {
    name: server.name,
    version: server.version,
    status: meta.status ?? null,
    ...(server.packages ? { packages: server.packages } : {}),
    ...(server.remotes ? { remotes: server.remotes } : {}),
  };
}

async function fetchRegistry() {
  const servers = [];
  const pageHashes = createHash('sha256');
  let cursor;
  let pages = 0;
  do {
    const params = new URLSearchParams({ limit: String(PAGE_LIMIT), version: 'latest' });
    if (cursor) params.set('cursor', cursor);
    const page = await fetchJson(`${REGISTRY_API}?${params}`);
    if (!Array.isArray(page.servers)) throw new Error('Unexpected registry response shape');
    pageHashes.update(JSON.stringify(page));
    servers.push(...page.servers.map(project));
    cursor = page.metadata?.nextCursor;
    pages++;
    if (pages % 50 === 0) console.error(`  fetched ${pages} pages, ${servers.length} servers`);
  } while (cursor);
  return {
    fetchedAt: new Date().toISOString(),
    source: `${REGISTRY_API}?version=latest&limit=${PAGE_LIMIT}`,
    pages,
    responseSha256: pageHashes.digest('hex'),
    servers,
  };
}

// ------------------------------------------------------ config generation

const SIMPLE_COMMAND = /^[A-Za-z0-9._-]+$/;
/** Origin label for any value this script invented rather than read from the
 * registry. Findings on such values say nothing about the registry and are
 * reported separately, never counted. */
const GENERATED = 'generated by this script';
const DEFAULT_RUNNER = { npm: 'npx', pypi: 'uvx', oci: 'docker', nuget: 'dnx' };

function asString(value) {
  return typeof value === 'string' ? value : value === undefined ? undefined : String(value);
}

/** Registry argument objects → argv. A value the publisher supplied (`value`,
 * else `default`) is used verbatim; a required argument with neither gets a
 * `<placeholder>`; an optional one with neither is left out, as a client
 * would. */
function renderArguments(list) {
  const argv = [];
  // Parallel to argv: true where the element is a placeholder this script
  // made up, so a finding on it can be told apart from one on real data.
  const generated = [];
  const push = (value, isGenerated) => {
    argv.push(value);
    generated.push(isGenerated);
  };
  for (const arg of list ?? []) {
    const value = asString(arg.value ?? arg.default);
    const placeholder = `<${arg.valueHint ?? arg.name ?? 'value'}>`;
    if (arg.type === 'positional') {
      if (value !== undefined) push(value, false);
      else if (arg.isRequired) push(placeholder, true);
    } else if (arg.type === 'named' && typeof arg.name === 'string') {
      if (value !== undefined) {
        push(arg.name, false);
        push(value, false);
      } else if (arg.isRequired) {
        push(arg.name, false);
        push(placeholder, true);
      }
    }
  }
  return { argv, generated };
}

/** A publisher-supplied value is real registry data and is kept; anything
 * else becomes a `${NAME}` reference, the form users write for "read this
 * from my environment" — never something a secret rule could match. */
function renderEnv(list) {
  const env = {};
  const generated = [];
  for (const variable of list ?? []) {
    if (typeof variable.name !== 'string') continue;
    const value = asString(variable.value ?? variable.default);
    env[variable.name] = value ?? `\${${variable.name}}`;
    if (value === undefined) generated.push(`env/${variable.name}`);
  }
  return { env, generated };
}

function packageSpec(pkg) {
  const { registryType, identifier, version } = pkg;
  if (!version) return identifier;
  switch (registryType) {
    case 'npm':
    case 'nuget':
    // uv accepts `name@version` as well as `name==version`; the `@` form is
    // what guardmcp's pin check (MCPG-105) understands, so a pinned PyPI
    // package is not reported as unpinned merely because of its syntax.
    case 'pypi':
      return `${identifier}@${version}`;
    case 'oci': {
      const lastSegment = identifier.split('/').pop() ?? identifier;
      return lastSegment.includes(':') || identifier.includes('@')
        ? identifier
        : `${identifier}:${version}`;
    }
    default:
      return identifier;
  }
}

/** Returns a stdio server definition, or a reason it cannot be expressed as
 * one. mcpb bundles are downloaded files and cargo crates need a build step:
 * neither has a launch command a config could contain. */
function renderPackage(pkg) {
  if (typeof pkg.identifier !== 'string' || pkg.identifier.length === 0) {
    return { skipped: 'missing identifier' };
  }
  const hint = typeof pkg.runtimeHint === 'string' ? pkg.runtimeHint.trim() : '';
  const command = SIMPLE_COMMAND.test(hint) ? hint : DEFAULT_RUNNER[pkg.registryType];
  if (!command) return { skipped: `registryType "${pkg.registryType}" has no launch command` };

  const runtime = renderArguments(pkg.runtimeArguments);
  const runtimeArgs = runtime.argv;
  const prefix = [];
  if (runtimeArgs.length === 0) {
    if (command === 'npx') prefix.push('-y');
    if (command === 'docker' || command === 'podman') prefix.push('run', '-i', '--rm');
  }
  const packaged = renderArguments(pkg.packageArguments);
  const packageArgs = packaged.argv;
  const args = [...prefix, ...runtimeArgs, packageSpec(pkg), ...packageArgs];
  // Parallel to `args`: which part of the registry entry each element came
  // from, so a finding on args/N can be traced back to what the publisher
  // actually wrote rather than to how this script assembled it.
  const argSources = [
    ...prefix.map(() => GENERATED),
    ...runtime.generated.map((g) => (g ? GENERATED : 'publisher runtimeArguments')),
    'package identifier + published version',
    ...packaged.generated.map((g) => (g ? GENERATED : 'publisher packageArguments')),
  ];
  const { env, generated } = renderEnv(pkg.environmentVariables);
  return {
    def: { command, args, ...(Object.keys(env).length > 0 ? { env } : {}) },
    argSources,
    generatedPaths: generated,
  };
}

function renderRemote(remote) {
  if (typeof remote.url !== 'string' || remote.url.length === 0) return { skipped: 'missing url' };
  const headers = {};
  const generatedPaths = [];
  for (const header of remote.headers ?? []) {
    if (typeof header.name !== 'string') continue;
    const value = asString(header.value ?? header.default);
    const fallback = `\${${header.name.toUpperCase().replace(/[^A-Z0-9]/g, '_')}}`;
    headers[header.name] = value ?? fallback;
    if (value === undefined) generatedPaths.push(`headers/${header.name}`);
  }
  return {
    def: { url: remote.url, ...(Object.keys(headers).length > 0 ? { headers } : {}) },
    generatedPaths,
  };
}

function buildConfig(server) {
  const mcpServers = {};
  const entries = [];
  (server.packages ?? []).forEach((pkg, i) => {
    const key = `package-${i}`;
    const rendered = renderPackage(pkg);
    entries.push({ key, kind: 'package', type: pkg.registryType ?? null, ...rendered });
    if (rendered.def) mcpServers[key] = rendered.def;
  });
  (server.remotes ?? []).forEach((remote, i) => {
    const key = `remote-${i}`;
    const rendered = renderRemote(remote);
    entries.push({ key, kind: 'remote', type: remote.type ?? null, ...rendered });
    if (rendered.def) mcpServers[key] = rendered.def;
  });
  return { config: { mcpServers }, entries };
}

// ----------------------------------------------------------------- scanning

async function runCli(args, cwd) {
  try {
    const { stdout, stderr } = await execFileAsync(process.execPath, [CLI, ...args], {
      cwd,
      maxBuffer: 512 * 1024 * 1024,
      env: { ...process.env, NO_COLOR: '1' },
    });
    return { code: 0, stdout, stderr };
  } catch (err) {
    // Exit 1 = findings at/above --fail-on; anything else is a real failure.
    if (err.code === 1) return { code: 1, stdout: err.stdout, stderr: err.stderr };
    throw new Error(`guardmcp scan failed (exit ${err.code}): ${err.stderr ?? err.message}`);
  }
}

async function scanAll(files, cwd) {
  const findings = [];
  const ruleMeta = new Map();
  const warnings = [];
  let targetsScanned = 0;
  for (let i = 0; i < files.length; i += SCAN_BATCH) {
    const batch = files.slice(i, i + SCAN_BATCH);
    const json = await runCli(['scan', '--format', 'json', '--fail-on', 'critical', ...batch], cwd);
    const report = JSON.parse(json.stdout);
    targetsScanned += report.targetsScanned;
    findings.push(...report.findings);
    warnings.push(...json.stderr.split('\n').filter((line) => line.trim().length > 0));

    // SARIF carries each fired rule's catalog entry, OWASP mapping included.
    const sarif = JSON.parse(
      (await runCli(['scan', '--format', 'sarif', '--fail-on', 'critical', ...batch], cwd)).stdout,
    );
    for (const rule of sarif.runs[0].tool.driver.rules) {
      ruleMeta.set(rule.id, {
        title: rule.shortDescription.text,
        level: rule.defaultConfiguration?.level ?? null,
        owasp: rule.properties?.owaspMcpTop10 ?? [],
        helpUri: rule.helpUri,
      });
    }
    for (const taxonomy of sarif.runs[0].taxonomies ?? []) {
      for (const taxon of taxonomy.taxa ?? []) ruleMeta.set(`taxon:${taxon.id}`, taxon.name);
    }
    console.error(`  scanned ${Math.min(i + SCAN_BATCH, files.length)}/${files.length}`);
  }
  return { findings, ruleMeta, warnings, targetsScanned };
}

// ----------------------------------------------------------- anonymization

const KEEP_HOSTS = /^(localhost|\[?[0-9a-f:.]+\]?)$/i;

/** Every string that could identify the server behind an example. */
function identifyingTokens(server) {
  const tokens = new Set();
  const add = (value) => {
    if (typeof value === 'string' && value.length >= 3) tokens.add(value);
  };
  add(server.name);
  for (const part of server.name.split(/[/.]/)) if (part.length >= 4) add(part);
  for (const pkg of server.packages ?? []) {
    add(pkg.identifier);
    for (const part of String(pkg.identifier ?? '').split(/[/@:]/)) if (part.length >= 4) add(part);
  }
  for (const remote of server.remotes ?? []) {
    try {
      const host = new URL(remote.url).hostname;
      add(host);
      for (const part of host.split('.')) if (part.length >= 4) add(part);
    } catch {
      add(remote.url);
    }
  }
  return [...tokens].sort((a, b) => b.length - a.length);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** URLs keep their scheme and, for loopback/IP-literal hosts, the host —
 * those carry the finding (cleartext, private address) and name nobody. */
function anonymize(text, server) {
  if (typeof text !== 'string') return text;
  let result = text.replace(/\b(https?|wss?):\/\/([^/\s"'`]+)([^\s"'`]*)/gi, (_m, scheme, host) => {
    const hostname = host.replace(/^[^@]*@/, '').replace(/:\d+$/, '');
    const port = /:(\d+)$/.exec(host)?.[1];
    const keep = KEEP_HOSTS.test(hostname);
    return `${scheme}://${keep ? hostname : '<host>'}${port ? `:${port}` : ''}/…`;
  });
  for (const token of identifyingTokens(server)) {
    result = result.replace(new RegExp(escapeRegExp(token), 'gi'), '<redacted>');
  }
  return result;
}

/** Coarse shape of a flagged value — separates a real literal from the
 * placeholder syntaxes publishers use for "fill this in yourself". */
function valueShape(value) {
  if (value === undefined) return 'no single value (e.g. whole entry)';
  if (/^\$\{[^}]+\}$/.test(value)) return `\${…} environment reference`;
  if (/\{[A-Za-z0-9_.-]+\}/.test(value)) return 'contains a {…} template placeholder';
  if (/^<[^>]+>$/.test(value)) return '<…> placeholder';
  return 'literal value';
}

/** Which part of the registry entry the flagged value came from. */
function originOf(entries, logicalPath) {
  const [, , key, field, index] = logicalPath.split('/');
  const entry = entries.find((e) => e.key === key);
  if (!entry) return 'unknown';
  if (entry.generatedPaths?.includes(`${field}/${index}`)) return GENERATED;
  if (field === 'args') return entry.argSources?.[Number(index)] ?? 'unknown';
  if (field === 'env') return 'publisher environmentVariables';
  if (field === 'headers') return 'publisher remote headers';
  if (field === 'url') return 'publisher remote url';
  if (field === 'command') return 'runtimeHint or runner default';
  return field ?? 'server entry';
}

function valueAt(config, logicalPath) {
  const parts = logicalPath.split('/').filter(Boolean);
  let node = config;
  for (const part of parts) {
    if (node === null || typeof node !== 'object') return undefined;
    node = node[part];
  }
  return typeof node === 'string' ? node : undefined;
}

// --------------------------------------------------------------- reporting

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'];
const nf = new Intl.NumberFormat('en-US');
const n = (value) => nf.format(value);

function countBy(items, key) {
  const counts = {};
  for (const item of items) {
    const k = key(item);
    counts[k] = (counts[k] ?? 0) + 1;
  }
  return counts;
}

function sortedEntries(record) {
  return Object.entries(record).sort((a, b) => b[1] - a[1] || String(a[0]).localeCompare(b[0]));
}

function mdEscape(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function buildSummary(
  snapshot,
  scanned,
  findingsByServer,
  ruleMeta,
  warnings,
  targetsScanned,
  artifacts,
) {
  const servers = snapshot.servers;
  const allFindings = [...findingsByServer.values()].flatMap((r) => r.findings);
  const byRule = {};
  for (const [name, record] of findingsByServer) {
    for (const f of record.findings) {
      byRule[f.ruleId] ??= { findings: 0, servers: new Set(), severity: {}, origin: {}, shape: {} };
      byRule[f.ruleId].findings++;
      byRule[f.ruleId].origin[f.origin] = (byRule[f.ruleId].origin[f.origin] ?? 0) + 1;
      byRule[f.ruleId].shape[f.valueShape] = (byRule[f.ruleId].shape[f.valueShape] ?? 0) + 1;
      byRule[f.ruleId].servers.add(name);
      byRule[f.ruleId].severity[f.severity] = (byRule[f.ruleId].severity[f.severity] ?? 0) + 1;
    }
  }
  const rules = Object.entries(byRule)
    .map(([id, v]) => ({
      id,
      title: ruleMeta.get(id)?.title ?? id,
      owasp: ruleMeta.get(id)?.owasp ?? [],
      findings: v.findings,
      servers: v.servers.size,
      severity: v.severity,
      origin: v.origin,
      shape: v.shape,
    }))
    .sort((a, b) => b.servers - a.servers || b.findings - a.findings || a.id.localeCompare(b.id));

  const owasp = {};
  for (const [name, record] of findingsByServer) {
    for (const f of record.findings) {
      for (const cat of ruleMeta.get(f.ruleId)?.owasp ?? []) {
        owasp[cat] ??= {
          title: ruleMeta.get(`taxon:${cat}`) ?? cat,
          findings: 0,
          servers: new Set(),
        };
        owasp[cat].findings++;
        owasp[cat].servers.add(name);
      }
    }
  }

  const entries = scanned.flatMap((s) => s.entries);
  return {
    registry: {
      source: snapshot.source,
      fetchedAt: snapshot.fetchedAt,
      pages: snapshot.pages,
      responseSha256: snapshot.responseSha256,
      servers: servers.length,
      byStatus: countBy(servers, (s) => s.status ?? 'unknown'),
      withPackagesOnly: servers.filter((s) => s.packages?.length && !s.remotes?.length).length,
      withRemotesOnly: servers.filter((s) => !s.packages?.length && s.remotes?.length).length,
      withBoth: servers.filter((s) => s.packages?.length && s.remotes?.length).length,
      withNeither: servers.filter((s) => !s.packages?.length && !s.remotes?.length).length,
      packagesByRegistryType: countBy(
        entries.filter((e) => e.kind === 'package'),
        (e) => e.type ?? 'unknown',
      ),
      remoteUrlSchemes: countBy(
        servers.flatMap((s) => s.remotes ?? []),
        (r) => /^([a-z][a-z0-9+.-]*):/i.exec(String(r.url ?? ''))?.[1]?.toLowerCase() ?? 'none',
      ),
      remotesByType: countBy(
        entries.filter((e) => e.kind === 'remote'),
        (e) => e.type ?? 'unknown',
      ),
    },
    scan: {
      guardmcpVersion: JSON.parse(readFileSync(join(REPO_ROOT, 'package.json'), 'utf-8')).version,
      serversWithAConfig: scanned.filter((s) => s.entries.some((e) => e.def)).length,
      serversWithoutAConfig:
        servers.length - scanned.filter((s) => s.entries.some((e) => e.def)).length,
      configFilesScanned: targetsScanned,
      entriesRendered: entries.filter((e) => e.def).length,
      entriesSkipped: countBy(
        entries.filter((e) => e.skipped),
        (e) => e.skipped,
      ),
      scannerWarnings: warnings.length,
      discardedOnGeneratedValues: {
        findings: artifacts.length,
        byRule: countBy(artifacts, (a) => a.ruleId),
      },
    },
    totals: {
      findings: allFindings.length,
      serversWithFindings: [...findingsByServer.values()].filter((r) => r.findings.length > 0)
        .length,
      bySeverity: countBy(allFindings, (f) => f.severity),
    },
    rules,
    owasp: Object.fromEntries(
      Object.entries(owasp)
        .sort((a, b) => a[0].localeCompare(b[0]))
        .map(([id, v]) => [id, { title: v.title, findings: v.findings, servers: v.servers.size }]),
    ),
  };
}

function pickExample(ruleId, findingsByServer, serverByName, configByName) {
  // Deterministic: the alphabetically first server that has this finding.
  for (const [name, record] of [...findingsByServer].sort((a, b) => a[0].localeCompare(b[0]))) {
    const finding = record.findings.find((f) => f.ruleId === ruleId);
    if (!finding) continue;
    const server = serverByName.get(name);
    const config = configByName.get(name);
    const value = valueAt(config, finding.logicalPath);
    const [, , key, field] = finding.logicalPath.split('/');
    const def = config?.mcpServers?.[key];
    // For an argument, the whole command line is the context that makes the
    // finding readable (e.g. an unpinned name ahead of the pinned spec).
    const commandLine =
      field === 'args' && def?.args
        ? [def.command, ...def.args].map((part) => anonymize(part, server)).join(' ')
        : undefined;
    return {
      ...(commandLine ? { commandLine } : {}),
      message: anonymize(finding.message, server),
      logicalPath: finding.logicalPath,
      ...(value !== undefined ? { value: anonymize(value, server) } : {}),
      ...(finding.evidence ? { evidence: anonymize(finding.evidence, server) } : {}),
    };
  }
  return undefined;
}

function renderReadme(summary, examples) {
  const { registry, scan, totals, rules, owasp } = summary;
  const lines = [];
  const push = (...l) => lines.push(...l);
  const severityLine = SEVERITY_ORDER.filter((s) => totals.bySeverity[s])
    .map((s) => `${n(totals.bySeverity[s])} ${s}`)
    .join(', ');

  push(
    '# The official MCP registry, scanned statically with guardmcp',
    '',
    "<!-- Generated by scripts/registry-scan.mjs — do not edit by hand. Every number below comes from that script's output. -->",
    '',
    `Snapshot of \`${registry.source}\` taken **${registry.fetchedAt}**, scanned with guardmcp **${scan.guardmcpVersion}** static rules. Raw data: [\`registry-snapshot.json.gz\`](./registry-snapshot.json.gz) (the exact input), [\`findings.json\`](./findings.json), [\`summary.json\`](./summary.json).`,
    '',
    '## Headline numbers',
    '',
    '| | Count |',
    '|---|---:|',
    `| Servers in the registry (latest version of each) | ${n(registry.servers)} |`,
    `| — published with packages only | ${n(registry.withPackagesOnly)} |`,
    `| — published with remote endpoints only | ${n(registry.withRemotesOnly)} |`,
    `| — published with both | ${n(registry.withBoth)} |`,
    `| — published with neither | ${n(registry.withNeither)} |`,
    `| Servers turned into a scannable config | ${n(scan.serversWithAConfig)} |`,
    `| Servers with at least one finding | ${n(totals.serversWithFindings)} |`,
    `| Findings in total | ${n(totals.findings)} |`,
    '',
    `Findings by severity: ${severityLine || 'none'}.`,
    '',
    `Remote endpoint URLs by scheme: ${sortedEntries(registry.remoteUrlSchemes)
      .map(([k, v]) => `${n(v)} ${k}`)
      .join(', ')}.`,
    '',
    `Registry status of the ${n(registry.servers)} servers: ${sortedEntries(registry.byStatus)
      .map(([k, v]) => `${n(v)} ${k}`)
      .join(', ')} (registry metadata, not a guardmcp finding).`,
    '',
    '## Findings per rule',
    '',
    'Ranked by the number of distinct servers affected. A server can have several findings for one rule (one per package or remote, or per argument).',
    '',
    '| Rule | Title | OWASP MCP | Servers | Findings |',
    '|---|---|---|---:|---:|',
  );
  for (const rule of rules) {
    push(
      `| [${rule.id}](../../rules/${rule.id}.md) | ${mdEscape(rule.title)} | ${rule.owasp.join(', ')} | ${n(rule.servers)} | ${n(rule.findings)} |`,
    );
  }
  push(
    '',
    'Rules that fired on no server are not listed. Rules that need a running server (`--live`: MCPG-2xx, 3xx tool rules, 404, 702, 8xx, 9xx), a lock file (MCPG-501/502), a registry lookup (`--registry`: MCPG-106) or a machine-wide view (MCPG-601) cannot fire in a static scan of generated configs and were not exercised.',
    '',
    '## OWASP MCP Top 10 distribution',
    '',
    'A rule can map to more than one category, so a finding is counted once in each of its categories; the rows do not sum to the total.',
    '',
    '| Category | Title | Servers | Findings |',
    '|---|---|---:|---:|',
  );
  for (const [id, v] of Object.entries(owasp)) {
    push(`| ${id} | ${mdEscape(v.title)} | ${n(v.servers)} | ${n(v.findings)} |`);
  }
  push('', 'Categories with no finding are omitted.', '', '## The ten most common issues', '');
  const top = rules.slice(0, 10);
  if (rules.length < 10) {
    push(
      `Only ${rules.length} rule(s) fired, so this list has ${rules.length} entr${rules.length === 1 ? 'y' : 'ies'}.`,
      '',
    );
  }
  top.forEach((rule, i) => {
    const example = examples[rule.id];
    push(
      `### ${i + 1}. ${rule.id} — ${rule.title}`,
      '',
      `${n(rule.servers)} server(s), ${n(rule.findings)} finding(s). OWASP: ${rule.owasp.join(', ') || '—'}.`,
      '',
      'Where the flagged value came from:',
      '',
      ...sortedEntries(rule.origin).map(([origin, count]) => `- ${origin}: ${n(count)}`),
      '',
      'Shape of the flagged value:',
      '',
      ...sortedEntries(rule.shape).map(([shape, count]) => `- ${shape}: ${n(count)}`),
      '',
    );
    if (example) {
      push(
        'Real example, anonymized (server, package and host names replaced with `<redacted>` / `<host>`):',
        '',
        '```text',
        example.message,
        `at ${example.logicalPath}${example.value !== undefined ? ` = ${JSON.stringify(example.value)}` : ''}`,
        ...(example.commandLine ? [`command line: ${example.commandLine}`] : []),
        ...(example.evidence ? [`evidence: ${example.evidence}`] : []),
        '```',
        '',
      );
    }
  });

  const skipped = sortedEntries(scan.entriesSkipped);
  push(
    '## Method',
    '',
    `1. **Collect.** Every page of \`${registry.source}\` was fetched (${n(registry.pages)} pages; SHA-256 of the concatenated responses \`${registry.responseSha256}\`). Only \`name\`, \`version\`, registry \`status\`, \`packages\` and \`remotes\` were kept; that projection is committed as \`registry-snapshot.json.gz\`.`,
    '2. **Render a config per server.** Each package and each remote becomes one entry under `mcpServers`, the way an MCP client would write it after installing the server:',
    "   - **Packages** become a stdio launch: the `runtimeHint` as the command when it is a single plain word, otherwise the registry type's runner (`npx -y` for npm, `uvx` for PyPI, `docker run -i --rm` for OCI, `dnx` for NuGet), then the runtime arguments, the package pinned to the published version (`name@version`; `image:version` for OCI), then the package arguments. PyPI pins use uv's `name@version` form, which guardmcp's pin check reads — `name==version` would have been misreported as unpinned.",
    '   - **Remotes** become `{ url, headers }`.',
    `   - **Values:** a \`value\` or \`default\` supplied by the publisher is used verbatim — it is what a user gets. Environment variables and headers without one become a \`\${NAME}\` reference; required arguments without one become \`<placeholder>\`; optional ones without one are omitted.`,
    `   - **Not representable:** ${skipped.length > 0 ? skipped.map(([k, v]) => `${n(v)} × ${k}`).join('; ') : 'none'}. These have no launch command a config can hold (an \`mcpb\` bundle is a downloaded file; a \`cargo\` crate needs a build step), so they were not scanned. ${n(scan.serversWithoutAConfig)} server(s) ended up with no scannable entry at all.`,
    `3. **Scan.** ${
      scan.discardedOnGeneratedValues.findings > 0
        ? `${n(scan.discardedOnGeneratedValues.findings)} finding(s) landed on a value this script generated (${sortedEntries(
            scan.discardedOnGeneratedValues.byRule,
          )
            .map(([k, v]) => `${n(v)} × ${k}`)
            .join(
              ', ',
            )}) and were discarded — they describe the rendering, not the registry; they are kept in \`findings.json\` under \`discarded\`. `
        : 'No finding landed on a value this script generated. '
    }The built guardmcp CLI ran \`scan --format json\` and \`scan --format sarif\` over the generated files in batches, with no \`--live\`, \`--registry\`, \`--lock\` or \`--baseline\`. ${n(scan.configFilesScanned)} config file(s) were scanned; the scanner emitted ${n(scan.scannerWarnings)} warning line(s). Rule titles and OWASP mappings are taken from the SARIF rule descriptors.`,
    '4. **Anonymize the examples.** Server names, package identifiers and remote host names (and their longer components) are replaced in each example; hosts that are loopback or IP literals are kept because they are the finding and identify no one. The raw `findings.json` is not anonymized: it is derived entirely from public registry data and is what makes the numbers checkable.',
    '',
    'Reproduce:',
    '',
    '```sh',
    'npm ci && npm run build',
    'node scripts/registry-scan.mjs --snapshot docs/research/registry-2026-09/registry-snapshot.json.gz --out /tmp/rescan',
    '# or, against the registry as it is today:',
    'node scripts/registry-scan.mjs --out /tmp/today',
    '```',
    '',
    '## Limitations',
    '',
    '- **Static, not live.** No server was started or contacted. Everything a server says about itself at runtime — tool descriptions, prompts, resources, whether an endpoint demands authentication — is invisible here. Tool poisoning, the attack this tool is mostly about, cannot appear in these numbers at all.',
    '- **The configs are reconstructions.** A user\'s real config depends on the client, on the values they fill in and on the version they choose. Findings describe what the registry entry leads to under the rendering rules above, not any particular installation. A different rendering (e.g. not pinning to the published version) would change the counts — MCPG-105 in particular: every package is pinned to its published version here, so it fires only where the publisher\'s own arguments name a package without a version (e.g. `npx --package <name> <bin>`, which installs whatever is current) or the published version is a moving tag — the "where the flagged value came from" lists above separate the two.',
    "- **False positives are possible.** The secret rules (MCPG-101/102) match patterns and entropy; a publisher's example value that looks like a key, or an intentionally public token, counts as a finding. The transport rules flag `http://` and private addresses that some servers legitimately use for local-only setups. None of the findings here were triaged by hand.",
    "- **False negatives too.** Anything not in the registry entry — the package's own code, its dependencies, what it does with the credentials it is given — is out of scope.",
    '- **One point in time.** The registry changes daily; the snapshot date above is the only date these numbers are valid for.',
    '',
  );
  return lines.join('\n');
}

// --------------------------------------------------------------------- main

async function main() {
  const options = parseArgs(process.argv.slice(2));
  if (!existsSync(CLI)) throw new Error(`${CLI} not found — run \`npm run build\` first.`);

  let snapshot;
  if (options.snapshot) {
    console.error(`Reading snapshot ${options.snapshot}`);
    snapshot = JSON.parse(gunzipSync(readFileSync(options.snapshot)).toString('utf-8'));
  } else {
    console.error(`Fetching ${REGISTRY_API} …`);
    snapshot = await fetchRegistry();
  }
  snapshot.servers.sort((a, b) => a.name.localeCompare(b.name));
  console.error(`${snapshot.servers.length} servers`);

  const work = mkdtempSync(join(tmpdir(), 'guardmcp-registry-'));
  try {
    const scanned = [];
    const files = [];
    const fileToServer = new Map();
    const configByName = new Map();
    const entriesByName = new Map();
    snapshot.servers.forEach((server, i) => {
      const { config, entries } = buildConfig(server);
      scanned.push({ server, entries });
      configByName.set(server.name, config);
      entriesByName.set(server.name, entries);
      if (Object.keys(config.mcpServers).length === 0) return;
      const file = `cfg/${String(i).padStart(6, '0')}.json`;
      mkdirSync(join(work, 'cfg'), { recursive: true });
      writeFileSync(join(work, file), JSON.stringify(config, null, 2));
      files.push(file);
      fileToServer.set(file, server.name);
    });

    const { findings, ruleMeta, warnings, targetsScanned } = await scanAll(files, work);

    const serverByName = new Map(snapshot.servers.map((s) => [s.name, s]));
    const findingsByServer = new Map();
    const artifacts = [];
    for (const finding of findings) {
      const file = relative(work, resolve(work, finding.location.file)).replace(/\\/g, '/');
      const name = fileToServer.get(file);
      if (!name) throw new Error(`Finding for unknown file ${finding.location.file}`);
      const origin = originOf(entriesByName.get(name) ?? [], finding.logicalPath);
      const value = valueAt(configByName.get(name), finding.logicalPath);
      const row = {
        ruleId: finding.ruleId,
        severity: finding.severity,
        confidence: finding.confidence,
        entry: finding.logicalPath.split('/')[2],
        logicalPath: finding.logicalPath,
        origin,
        valueShape: valueShape(value),
        message: finding.message,
        ...(finding.evidence ? { evidence: finding.evidence } : {}),
      };
      if (origin === GENERATED) {
        artifacts.push({ server: name, ...row });
        continue;
      }
      const record = findingsByServer.get(name) ?? { findings: [] };
      record.findings.push(row);
      findingsByServer.set(name, record);
    }

    const summary = buildSummary(
      snapshot,
      scanned,
      findingsByServer,
      ruleMeta,
      warnings,
      targetsScanned,
      artifacts,
    );
    const examples = {};
    for (const rule of summary.rules.slice(0, 10)) {
      examples[rule.id] = pickExample(rule.id, findingsByServer, serverByName, configByName);
    }
    summary.examples = examples;

    mkdirSync(options.out, { recursive: true });
    writeFileSync(
      join(options.out, 'registry-snapshot.json.gz'),
      gzipSync(JSON.stringify(snapshot), { level: 9 }),
    );
    writeFileSync(
      join(options.out, 'findings.json'),
      `${JSON.stringify(
        {
          fetchedAt: snapshot.fetchedAt,
          guardmcpVersion: summary.scan.guardmcpVersion,
          servers: [...findingsByServer]
            .sort((a, b) => a[0].localeCompare(b[0]))
            .map(([name, record]) => ({
              name,
              version: serverByName.get(name)?.version,
              config: configByName.get(name),
              findings: record.findings,
            })),
          discarded: artifacts,
          scannerWarnings: warnings,
        },
        null,
        1,
      )}\n`,
    );
    writeFileSync(join(options.out, 'summary.json'), `${JSON.stringify(summary, null, 2)}\n`);
    writeFileSync(join(options.out, 'README.md'), renderReadme(summary, examples));
    console.error(
      `Done: ${summary.totals.findings} findings on ${summary.totals.serversWithFindings} of ${summary.registry.servers} servers → ${options.out}`,
    );
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
