import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { PACKAGE_VERSION } from '../../package-info.js';
import { EXIT_CODES } from '../exit-codes.js';

export const WORKFLOW_PATH = '.github/workflows/guardmcp.yml';

export interface InitCommandOptions {
  readonly cwd: string;
  readonly force?: boolean;
  readonly failOn?: string;
  readonly stdout: (text: string) => void;
  readonly stderr: (line: string) => void;
}

/**
 * Writes a working GitHub Actions workflow.
 *
 * The gap between "this tool would help us" and "this tool runs on every PR"
 * is usually one file nobody gets around to writing. `--live` is deliberately
 * NOT enabled in the generated workflow: it spawns each server's launch
 * command, which is a decision a repository owner should make knowingly
 * rather than inherit from a generator.
 */
function workflow(failOn: string): string {
  return `# Generated by \`guardmcp init\` (v${PACKAGE_VERSION}).
# Scans this repository's MCP server configs on every push and pull request,
# and uploads the results to GitHub Code Scanning.
name: guardmcp

on:
  push:
    branches: [main, master]
  pull_request:
  # Configs change when dependencies do, not only when someone edits them —
  # a weekly run catches a server that started advertising something new.
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read
  # Required to upload the SARIF report; without it the scan runs but the
  # findings never reach the Security tab.
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan MCP configs
        id: guardmcp
        uses: BerkantACUN/guardmcp@v${PACKAGE_VERSION}
        with:
          fail-on: ${failOn}
          sarif-output: guardmcp-results.sarif
        # Upload the SARIF even when the scan fails the build, so the findings
        # are readable in the Security tab rather than only in the job log.
        continue-on-error: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: guardmcp-results.sarif
          category: guardmcp

      - name: Fail if guardmcp found issues
        if: steps.guardmcp.outcome == 'failure'
        run: exit 1
`;
}

export function runInitCommand(options: InitCommandOptions): number {
  const failOn = options.failOn ?? 'high';
  const target = join(options.cwd, WORKFLOW_PATH);

  if (existsSync(target) && options.force !== true) {
    options.stderr(`${WORKFLOW_PATH} already exists. Re-run with --force to overwrite it.`);
    return EXIT_CODES.toolError;
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, workflow(failOn), 'utf-8');

  options.stdout(
    [
      `Wrote ${WORKFLOW_PATH}`,
      '',
      'It scans on every push and pull request, uploads findings to the Security',
      `tab, and fails the build at severity "${failOn}" or above.`,
      '',
      'Two things it deliberately does not do, which you may want:',
      '  --live   connects to each server and scans its real tools, prompts and',
      '           resources. It spawns their launch commands, so enabling it is',
      "           your call, not a generator's.",
      '  pin      run `guardmcp pin` and commit .mcpguard-lock.json to turn on',
      '           rug-pull detection (MCPG-501/502).',
      '',
    ].join('\n'),
  );
  return EXIT_CODES.clean;
}
